<?php
$this->headTitle('News - Edit News');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
?>

<div class="page-header">
    <h1>News <small>Edit News </small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a  href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'index'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to all news</a>

                </div>  
            </div>
            <div class="panel-body">

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="update">

                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit News - <?php echo $this->escape($this->news['title']) ?></legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="title">Title</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => "enter news\'s title",
                                    'id' => 'title',
                                    'required' => 'required'
                                ));
                                ?>

                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>

                            <div class="col-md-4">
                                <?php if ($form->getElement('title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="description">Description</label>
                            <div class="col-md-4"> 

                                <?php
                                echo $form->getElement('description')->setAttribs(array(
                                    'class' => 'form-control',
                                    'id' => 'description',
                                    'rows' => 12
                                ));
                                ?>

                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('description')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Image -->

                        <div class="form-group">
                            <label class="col-md-4 control-label" for="news_photo">Photo</label>
                            <div class="col-md-4"> 
                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->newsImgUrl($this->news); ?>">
                                    </a>

                                </div>
                                <input type="file" name="news_photo" id="news_photo" class="form-control  input-md">
                                <span class="help-block">Change Photo</span>

                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('news_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('news_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_news_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a 
                                    href ="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'index'), 'default', true) ?>"
                                    id="new_news_cancel" name="new_news_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_news_submit" name="new_news_submit" class="btn btn-success">Save</button>
                            </div>

                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>
