<?php
$this->headTitle(' News');
?>
<div class="page-header">
  <h1> News</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<button data-action="save-order" class="btn btn-success" style="display: none;">
						<i class="glyphicon glyphicon-save"></i>
						Save Order
					</button>
					<button data-action="toggle-sort" class="btn btn-default">
						<i class="glyphicon glyphicon-list"></i>
						Change Order
					</button>
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'add'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add News</a>
				</div>
			</div>	
				
                    <div class="panel-body">
                        <table id="rows-table" class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th class="text-center">Img</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Title</th>
                                    <th class="text-center">#</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($this->news as $news) {
                                    if ($news['status'] == Application_Model_DbTable_CmsNews::STATUS_DISABLED) {
                                        ?>

                                        <tr class="danger" data-news-id="<?php echo $this->escape($news['id']); ?>" >
                                            <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
                                            <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->newsImgUrl($news); ?>"></td>
                                            <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                                            <td class="text-center"><?php echo $this->escape($news['title']); ?></td>
                                            <td class="text-center">
                                                <div class="btn-group btn-group" role="group" aria-label="...">
                                                    <a 
                                                        href="<?php echo $this->url(array('controller' => 'news', 'action' => 'index'), 'default', true); ?>" 
                                                        target="_blank"
                                                        type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                                    <a 
                                                        href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'edit', 'id' => $news['id']), 'default', true); ?>" 
                                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                                    <button data-newsName="<?php echo $this->escape($news['title']); ?>" data-news-id="<?php echo $this->escape($news['id']); ?>" type="button" class="btn btn-default" title="enable" data-action="enable"><i class="glyphicon glyphicon-ok"></i></button>

                                                    <button data-newsName="<?php echo $this->escape($news['title']); ?>" data-news-id="<?php echo $this->escape($news['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                                                </div>
                                            </td>
                                        </tr>
                                        <?php
                                    } else {
                                        ?>
                                        <tr data-news-id="<?php echo $this->escape($news['id']); ?>" >
                                            <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
                                            <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->newsImgUrl($news); ?>"></td>
                                            <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                                            <td class="text-center"><?php echo $this->escape($news['title']); ?></td>
                                            <td class="text-center">
                                                <div class="btn-group btn-group" role="group" aria-label="...">
                                                    <a 
                                                        href="<?php echo $this->url(array('controller' => 'news', 'action' => 'index'), 'default', true); ?>" 
                                                        target="_blank"
                                                        type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                                    <a 
                                                        href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'edit', 'id' => $news['id']), 'default', true); ?>"
                                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                                    <button data-newsName="<?php echo $this->escape($news['title']); ?>" data-news-id="<?php echo $this->escape($news['id']); ?>" type="button" class="btn btn-default" title="disable" data-action="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                                    <button data-newsName="<?php echo $this->escape($news['title']); ?>" data-news-id="<?php echo $this->escape($news['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                                </div>
                                            </td>
                                        </tr>

                                        <?php
                                    }
                                    ?> 


                                    <?php
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
			
		</div>
	</div>
</div>

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'delete'), 'default', true);?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
	<input type="hidden" name="task" value="delete">
	<input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete news</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete news?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'disable'), 'default', true);?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
	<input type="hidden" name="task" value="disable">
	<input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable news</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable news?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'enable'), 'default', true);?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
	<input type="hidden" name="task" value="enable">
	<input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable news</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable news?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-remove"></i> Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'updateorder'), 'default', true);?>" style="display: none;" id="save-order-form">
	<input type="hidden" name="task" value="saveOrder">
	<input type="hidden" name="sorted_ids" value="">
</form>
<?php
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
	
	$('#rows-table').on('click', '[data-action="delete"]', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//calculate target element
		var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
		
		//get any attribute
		var newsId = target.attr('data-news-id');
		
		//get data- attributes
		var newsId = target.data('news-id');
		
		
		//set value for input field with name "id"
		$('#delete-warning-dialog').find('[name="id"]').val(newsId);
		
		$('#delete-warning-dialog').modal('show');
	});
	
	$('#rows-table').on('click', '[data-action="disable"]', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//calculate target element
		var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
		
		//get any attribute
		var newsId = target.attr('data-news-id');
		
		//get data- attributes
		//var newsId = target.data('newsId');
		
		
		//set value for input field with name "id"
		$('#disable-warning-dialog').find('[name="id"]').val(newsId);
		
		$('#disable-warning-dialog').modal('show');
	});
	
	$('#rows-table').on('click', '[data-action="enable"]', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//calculate target element
		var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
		
		//get any attribute
		var newsId = target.attr('data-news-id');
		
		//get data- attributes
		//var newsId = target.data('newsId');
		
		
		//set value for input field with name "id"
		$('#enable-warning-dialog').find('[name="id"]').val(newsId);
		
		$('#enable-warning-dialog').modal('show');
	});
	
	$('[data-action="toggle-sort"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');
		
		var sortableTbody = $('#rows-table > tbody');
		
		if (target.hasClass('active')) {
			
			target.removeClass('active');
			
			target.html('<i class="glyphicon glyphicon-list"></i> Change Order');
			
			// destroy sortable functionallity
			sortableTbody.sortable('destroy');
			
			// restore old html into tbody
			sortableTbody.html(sortableTbody.data('oldHtml'));
			
			//hide "handle" for sorting, the icon in first column
			sortableTbody.find('[data-action="sort"]').hide();
			
			//hide "Save Order" button
			$('[data-action="save-order"]').hide();
			
		} else {
			
			target.addClass('active');
			
			//method html sets or gets html inside selected element
			target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
			
			//save tbody html before sorting under key "oldHtml" into its data
			sortableTbody.data('oldHtml', sortableTbody.html());
			
			//initialize sortable functionallity
			sortableTbody.sortable({
				handle: '[data-action="sort"]'
			});
			
			//show "handle" for sorting, the icon in first column
			sortableTbody.find('[data-action="sort"]').show();
			
			//show "Save Order" button
			$('[data-action="save-order"]').show();
		}
	});
	
	$('[data-action="save-order"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		var newsSortedIds = $('#rows-table > tbody').sortable('toArray', {
			attribute: 'data-news-id'
		});
		
		//select save order form
		var saveOrderForm = $('#save-order-form');
		
		//find element with name "sorted_ids" in save order form and set its value
		// with string in wich are sorted ids separated with coma (,)
		// ex. "12,3,8,10,11,6,2,1,9,7,5,4"
		saveOrderForm.find('[name="sorted_ids"]').val(newsSortedIds.join(','));
		
		// manually submit form by triggering "submit" event
		saveOrderForm.trigger('submit');
	});
	
<?php $this->inlineScript()->captureEnd(); ?>
</script>
