<?php
$sitemapPage = $this->sitemapPage;
$news = $this->news;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>

<div class="container">
    <article>
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
            <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
            <?php } ?>
        </ol>
    </article>
</div>       
<main>
    <section class="news newsPage">
        <div class="container">
            <div class="row">
                <?php foreach ($news as $singleNews) {
                    ?>
                    <div class="col-sm-6 col-md-4">
                        <figure class="newsItem">
                            <div class="imgNews">
                                <img class="img-responsive" src="<?php echo $this->newsImgUrl($singleNews); ?>" alt=""/>
                                <div class="hoverNews text-center">
                                    <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                </div>
                            </div>

                            <button type="button" class="btn items date"><?php echo $this->escape($singleNews['date']); ?></button>
                            <button type="button" class="btn items article"> View Article <?php echo $this->escape($singleNews['title']); ?></button>
                            <br>
                            <p><span><?php echo $this->escape($singleNews['description']); ?>
                                </span></p>


                        </figure>
                    </div>
                <?php }
                ?>
            </div>
        </div>
    </section>
</main>