<?php
$sitemapPage = $this->sitemapPage;
$services = $this->services;
$this->headTitle($sitemapPage['title']);
?>

<div id="highlighted">
    <div class="container">
        <?php echo $this->headTitle('Services'); ?>
        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
    </div>
</div>

<section class="news newsPage">
    <div class="container">
        <div class="row">
            <?php foreach ($services as $service) {
                ?>
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="<?php echo $this->serviceImgUrl($service);?>" alt="">
                            <div style="display: none;" class="hoverNews text-center">
<!--                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>-->
                            </div>
                        </div>
                        <a href="#"><?php echo $this->escape($service['title']); ?></a>
                        <br>
                        <span><?php echo $this->escape($service['description']); ?>
                        </span>
                    </figure>
                </div>
            <?php }
            ?>
        </div>
    </div>
</section>
