
<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);
?>

<main>
    <div class="container">

        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
<!--        <div class="header-a">
            //
        </div>-->
        <p>
            <?php echo $sitemapPage['body']; ?>
        </p>
    </div>
</main>