<?php
$this->headTitle('Products - Edit Product');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper')); 
?>
<div class="page-header">
    <h1>Products</h1>
    <small>Edit Product</small>
</div>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true) ?>' 
                        class="btn btn-default">
                        <i class="glyphicon glyphicon-arrow-left"></i>Back to all products</a>
                </div>

            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="update">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Product - <?php echo $this->escape($this->product['first_name'] . ' ' . $this->product['last_name']); ?></legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First Name</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('first_name')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s first name',
                                    'id' => 'first_name',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('first_name')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('first_name')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?> 
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('last_name')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s last name',
                                    'id' => 'last_name',
                                    'required' => 'required'
                                ));
                                ?>

                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('last_name')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('last_name')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('email')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s email',
                                    'id' => 'email',
                                    'required' => 'required'
                                ));
                                ?>

                                <span class="help-block">username@domain</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('email')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="work_title">Work Title</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('work_title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s work title',
                                    'id' => 'work_title'
                                ));
                                ?>

                                <span class="help-block">ex. "senior web developer"</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('work_title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('work_title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Resume</label>
                            <div class="col-md-4">                     
                                <?php
                                echo $form->getElement('resume')->setAttribs(array(
                                    'class' => 'form-control',
                                    'id' => 'resume',
                                    'rows' => 12
                                ));
                                ?>
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('resume')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('resume')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>  
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label" for="product_photo">Photo</label>
                            <div class="col-md-4">  
                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->productImgUrl($this->product); ?>">
                                    </a>
                                </div>
                                <input type="file" name="product_photo" id="product_photo" class="form-control input-md">
                                <span class="help-block">change photo</span>
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('product_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('product_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>  
                            </div>
                        </div>
                        <!-- Button (Double) -->
                        <div class="form-group text-right">
                            <label class="col-md-4 control-label" for="new_product_cancel"></label>
                            <div class="col-md-8">
                                <a href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true); ?>" id="new_product_cancel" name="new_product_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_product_submit" name="new_product_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>