<?php
$this->headTitle('Products');
?>
<div class="page-header">
    <h1>Products</h1>
</div>
<div class="row">
    <div class="col-lg-12" id="system-messages-container">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'add'), 'default', true); ?>"
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add product</a>
                </div>
            </div>
            <div class="panel-body">

                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th class="text-center">Stockpile </th>
                            <th>Action</th>
                            <th>Model</th>
                            <th>Type</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Discount</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php /*
                          foreach ($this->products as $product) {
                          if ($product['status'] == Application_Model_DbTable_CmsProducts::STATUS_DISABLED) {
                          ?>
                          <tr data-product-id="<?php echo $this->escape($product['id']);?>" class="danger">
                          <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                          <td><?php echo $this->escape($product['productname']);?></td>
                          <td><?php echo $this->escape($product['first_name']);?></td>
                          <td><?php echo $this->escape($product['last_name']);?></td>
                          <td><?php echo $this->escape($product['email']);?></td>
                          <td class="text-center">
                          <div class="btn-group btn-group-sm" role="group" aria-label="...">
                          <a
                          href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'edit', 'id' => $product['id']), 'default', true);?>"
                          type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                          </div>
                          </td>
                          </tr>
                          <?php
                          } else {
                          ?>
                          <tr data-product-id="<?php echo $this->escape($product['id']);?>">
                          <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                          <td><?php echo $this->escape($product['productname']);?></td>
                          <td><?php echo $this->escape($product['first_name']);?></td>
                          <td><?php echo $this->escape($product['last_name']);?></td>
                          <td><?php echo $this->escape($product['email']);?></td>
                          <td class="text-center">
                          <div class="btn-group btn-group-sm" role="group" aria-label="...">
                          <a
                          href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'edit', 'id' => $product['id']), 'default', true);?>"
                          type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="reset-password" type="button" class="btn btn-default" title="reset"><i class="fa fa-unlock-alt"></i></button>
                          <button data-product-name="<?php echo $this->escape($product['first_name']) . " " . $this->escape($product['last_name']);?>" data-product-id="<?php echo $this->escape($product['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                          </div>
                          </td>
                          </tr>
                          <?php
                          }
                          ?>

                          <?php
                          }
                         */ ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete product <span id="delete-product"></span>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i>Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Disable product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to disable product <span id="disable-product"></span>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i>Disable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Enable product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to enable product <span id="enable-product"></span>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i>Enable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<div id="message-templates" style="display: none">
    <div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>

    <div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>


</div>
<?php
  $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));
  $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
?>

<?php
//$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css'));
////$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-responsive/css/dataTables.responsive.css'));
//$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables/media/js/jquery.dataTables.min.js'));
//$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js'));
//$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-responsive/js/dataTables.responsive.js'));
//?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
    $('#rows-table').on('click', '[data-action="delete"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        //calculate target element
        var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');

        var productId = target.attr('data-product-id');
        var productName = target.attr('data-product-name');
   
        $('#delete-warning-dialog').find('[name="id"]').val(productId);
        $('#delete-product').text(productName);
        $('#delete-warning-dialog').modal('show');
    });
    $('#rows-table').on('click', '[data-action="disable"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        //calculate target element
        var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
        var productName = target.attr('data-product-name');
        var productId = target.attr('data-product-id');
        //.val je funkcija za dodeljivanje vrednosti elemenata forme u ovom slucaju za polje sa nazivom "id"
        $('#disable-warning-dialog').find('[name="id"]').val(productId);
        $('#disable-product').text(productName);
        $('#disable-warning-dialog').modal('show');
    });
    $('#rows-table').on('click', '[data-action="enable"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        //calculate target element
        var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
        var productName = target.attr('data-product-name');
        var productId = target.attr('data-product-id');
        $('#enable-warning-dialog').find('[name="id"]').val(productId);
        $('#enable-product').text(productName);
        $('#enable-warning-dialog').modal('show');
    });


    $('#rows-table').DataTable({
        columnDefs: [
            {targets: [6], orderable: false, searchable: false}, 
            {targets: [0, 5], className: 'text-center'}
        ],
        order: [
            [2, 'asc']
        ],
        lengthMenu: [10, 20, 50, 100],
        serverSide: true,
        processing: true,
        ajax: "<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'datatable'), 'default', true); ?>"//gde pitamo server
    });

    $('#disable-warning-dialog').on('submit', function (e) {

        e.preventDefault();//stop manual form submit

        var target = $(this).is('#disable-warning-dialog') ? $(this) : $(this).closest('#disable-warning-dialog');

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'disable'), 'default', true) ?>',
            method: 'post',
            data: {
                task: 'disable',
                id: target.find('[name="id"]').val()

            }


        }).done(function (data) {

            if (data['status'] === 'ok') {

                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);
                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

                $('#system-messages-container').append(messageBox);
                //alert('Succes: ' + data['statusMessage']);
                messageBox.delay(5000).fadeOut();
            } else {
                //var messageBox = $('[data-container="message-box-error"]').last().clone(true);
                var messageBox = $('#message-templates [data-container="message-box-error"]').clone(true);

                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);
                //$('#system-messages-container').empty(); zatvora prethodnu poruku za producta
                $('#system-messages-container').append(messageBox);
                //alert('Error: ' + data['statusMessage']);
                messageBox.delay(5000).fadeOut();
            }


        }).fail(function () {
            //error in communication with server
            alert('Error:Server returned error')


        }).always(function () {
            target.modal('hide');
            //refresh table keep selected page
            $('#rows-table').DataTable().draw(false);
        });
    });

    $('#enable-warning-dialog').on('submit', function (e) {

        e.preventDefault();//stop manual form submit
        
        var target = $(this).is('#enable-warning-dialog') ? $(this) : $(this).closest('#enable-warning-dialog');
        
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'enable'), 'default', true) ?>',
            method: 'post',
            data: {
                task: 'enable',
                id: target.find('[name="id"]').val()

            }


        }).done(function (data) {
            if (data['status'] === 'ok') {

                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);//kloniraj i handler u message boxu
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);

                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

                $('#system-messages-container').append(messageBox);

                messageBox.delay(5000).fadeOut();

            } else {
                //var messageBox = $('[data-container="message-box-error"]').last().clone(true);
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);

                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

                $('#system-messages-container').append(messageBox);

                messageBox.delay(5000).fadeOut();

            }


        }).fail(function () {
            //error in communication with server
            alert('Error:Server returned error')


        }).always(function () {
            target.modal('hide');
            $('#rows-table').DataTable().draw(false);
        });
    });

    $('#delete-warning-dialog').on('submit', function (e) {

        e.preventDefault();

        var target = $(this).is('#delete-warning-dialog') ? $(this) : $(this).closest('#delete-warning-dialog');

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'delete'), 'default', true) ?>',
            method: 'post',
            data: {
                task: 'delete',
                id: target.find('[name="id"]').val()

            }

        }).done(function (data) {

            if (data['status'] === 'ok') {

                //var messageBox = $('[data-container="message-box-success"]').last().clone(true);
                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);

                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

                $('#system-messages-container').append(messageBox);

                messageBox.delay(5000).fadeOut();

            } else {
                // var messageBox = $('[data-container="message-box-error"]').last().clone(true);

                var messageBox = $('#message-templates').find('[data-container="message-box-success"]').clone(true);

                messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

                $('#system-messages-container').append(messageBox);

                messageBox.delay(5000).fadeOut();

            }
        }).fail(function () {

            alert('Error:Server returned error')

        }).always(function () {
            target.modal('hide');

            $('#rows-table').DataTable().draw(false);
        });
    });

<?php $this->inlineScript()->captureEnd(); ?>
</script>