<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
    </div>
<main class="contactUs">
    <section class="googleMap">
        <div class="mapWrapper">
            <div id='gmap_canvas' ></div>		  
        </div>

        <div class="formWrapp">

            <div class="formContact">
                <h2>Contact Us</h2>
                <div class="row">
                    <div class="col-lg-6 contactImg text-center">
                        <img class="img-responsive" src="/front/img/contact.jpg" alt=""/>
                    </div>

                    <div class="col-lg-6">
                        <div class="adress">
                            <h3>+381111234567890</h3>
                            <p>MIHAILO PUPIN BLVD., BELGRADE, PC 11000</p>
                        </div>
                    </div>
                </div>

                <form class="form-group">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Name" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Email" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-xs-4">
                            <div class="input-group">
                                <button class="btn btn-default formBtn" type="submit">Contact Us</button>
                            </div><!-- /input-group -->
                        </div>

                    </div><!-- /.row -->
                </form>			    
            </div>
        </div>
    </section>
    <section class="location">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i>Choose another location:</p>
                </div>
                <div class="col-md-9">
                    <select id="locationStore" class="form-control">
                        <option value="1">MIHAILO PUPIN BLVD., BELGRADE, PC 11000</option>
                        <option value="2">MIHAILO PUPIN BLVD., BELGRADE, PC 11000</option>
                        <option value="3">MIHAILO PUPIN BLVD., BELGRADE, PC 11000</option>
                    </select>

                </div>
            </div>

        </div>
    </section>
    <section class="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <p><img  src="front/img/mail_icon.png" alt=""/><a href="mailto:school@cubes.rs"> email@email.com</a></p>

                </div>
                <div class="col-md-4">
                    <p><img  src="front/img/skype_icon.png" alt=""/>gear.psdtemplate</a></p>
                </div>
                <div class="col-md-4">
                    <p><img  src="front/img/phone_icon_1.png" alt=""/>+381111234567890</p>
                </div>
            </div>
        </div>

    </section>
<!--    <section class="information">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <h3>Catalog</h3>
                    <div class="row">
                        <div class="col-md-4">
                            <p><a href="">Interior</a></p>
                            <p><a href="">Exterior</a></p>
                            <p><a href="">Performance</a></p>
                            <p><a href="">Lighting</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">Wheels & Tires</a></p>
                            <p><a href="">Audio</a></p>
                            <p><a href="">Repair Parts</a></p>
                            <p><a href="">Body Parts</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">RV Parts</a></p>
                            <p><a href="">Tools & Garage</a></p>
                            <p><a href="">Outdoor</a></p>
                        </div>
                    </div>

                </div>
                <div class=" col-md-3">
                    <h3>Delivery Information</h3>
                    <p><a href="">Delivery Information</a></p>
                    <p><a href="">Privacy policy</a></p>
                    <p><a href="">Terms & Condition</a></p>
                    <p><a href="">Contact us</a></p>

                </div>
                <div class=" col-md-3">
                    <h3>Our service</h3>
                    <p><a href="">My Account</a></p>
                    <p><a href="">Returns</a></p>
                    <p><a href="">Site map</a></p>
                </div>
            </div>
        </div>
    </section>           -->
</main>
